ldap_server vives_ldap {
    url ldap://192.168.200.50:389/ou=users,dc=iesluisvives,dc=org?uid?sub?(objectClass=*);
    binddn "cn=admin,dc=iesluisvives,dc=org";
    bindpw "admin";
    require valid_user;
}

server {
    listen 80;
    server_name iesluisvives.org;

    location /daw/ {
        proxy_pass http://192.168.200.20/;
    }

    location /daw/calificaciones/ {
        auth_ldap "Acceso Restringido - Alumnos";
        auth_ldap_servers vives_ldap;
        proxy_pass http://192.168.200.20/calificaciones/;
    }

    location /dam/ {
        proxy_pass http://192.168.200.30/;
    }

    location /dam/calificaciones/ {
        auth_ldap "Acceso Restringido - Alumnos";
        auth_ldap_servers vives_ldap;
        proxy_pass http://192.168.200.30/calificaciones/;
    }
}